### **Hardware & Physics Terminology**

* **Neutral-Atom Qubits:** Qubits formed by uncharged atoms (such as Rubidium or Strontium) suspended in a vacuum by focused laser beams (optical tweezers). They differ from superconducting qubits by allowing flexible 2D/3D connectivity and naturally supporting heralded error detection.
* **Rydberg State / Rydberg Blockade:** A highly excited atomic energy state used to perform two-qubit entangling gates. When one atom is excited to a Rydberg state, its physical presence shifts the energy levels of nearby atoms, "blockading" them from being simultaneously excited.
* **Correlated $ZZ$ Error:** A specific noise signature resulting from imperfect Rydberg laser pulses. When a two-qubit gate fails via blockade imperfections, it often leaves a simultaneous phase flip ($Z$ error) on both interacting atoms, creating a highly localized, paired error that neural networks can learn to recognize.
* **Erasure (Atom Loss):** A severe error mode where an atom is either physically knocked out of its optical tweezer (e.g., via background gas collisions) or excited into a non-computational "dark state." In the simulation, this is modeled as a maximally mixed state (a strong depolarizing channel).

### **Quantum Error Correction (QEC)**

* **Syndrome:** The parity data extracted from the quantum computer to detect errors without collapsing the underlying quantum information. In the machine learning pipeline, the syndrome record represents the primary input tensor ($X_1$) fed to the neural network.
* **Herald (Heralded Error):** A classical flag generated by the hardware mid-circuit to explicitly broadcast that an erasure has occurred at a known time and location (e.g., via a missing fluorescence signal). This acts as a secondary input channel ($X_2$) for the neural decoder.
* **Logical Observable:** The actual, protected quantum information the surface code is trying to preserve. Whether this observable unexpectedly flips at the end of a simulation serves as the binary ground-truth label ($y$) for training the Transformer.
* **Detector:** A point in space and time within the circuit where a parity measurement unexpectedly changes value between rounds, indicating an error has occurred nearby. The sparsity of these detector flashes dictates the input sparsity for the neural network.

### **Software & Algorithmic Terminology**

* **Stim:** An ultra-fast, open-source quantum circuit simulator developed by Google that tracks how errors propagate through Clifford circuits. It is the data-generation engine for the project, producing the millions of training shots required for deep learning.
* **Detector Error Model (DEM):** A graphical representation generated by Stim that maps physical error probabilities to the likelihood of specific detector sets firing. Modifying circuits to include native erasures shifts measurement indices and breaks the DEM, which is why the pipeline manages erasure heralds via a parallel Python array.
* **MWPM (Minimum-Weight Perfect Matching):** The traditional graph-based algorithm used for decoding surface codes, acting as the performance baseline. MWPM struggles with neutral-atom noise because it requires computationally expensive, dynamic edge-weight recalculations to process erasures and cannot easily group correlated $ZZ$ errors.
* **PyMatching:** An open-source, highly optimized Python/C++ implementation of the MWPM algorithm.
* **Transformer Decoder:** An attention-based neural network architecture (originating from NLP and utilized by Google's AlphaQubit) that frames error correction as a sequence classification problem. By processing syndromes and heralds as multi-channel tokens, the self-attention mechanism natively learns the complex, structured hardware noise correlations that traditional algorithms miss.